PaulPugovkin/netflix-killer-project

- src/index.js
- src/js/fetch-my-library.js
- src/js/get-refs.js
- src/js/pagination.js
- src/js/render-card-movie.js
- src/js/return-home-logo.js
- src/partials/header.html
- src/sass/modules/_header.scss
Добавлена активная кнопка возврата на главную страницу по HOME и LOGO с рисовкой карточек популярных.
Далее буду думать о плавной смене картинки  bgraund
> fetch-render-main-header

- src/index.js
- src/js/fetch-on-click-movie.js
- src/js/get-refs.js
- src/js/modal-open.js
- src/partials/modal.html
- src/templates/movie-card.hbs
- src/templates/movie-modal-card.hbs
сделал модалку, при открытии рендерится информация о фильме
нужно будет подкрутить стили
> on open movie card

- package-lock.json
- package.json
- src/index.js
- src/js/fetch-on-click-movie.js
- src/js/get-refs.js
- src/js/modal-open.js
- src/js/render-card-movie.js
- src/js/spinner.js
Знаю, не надо совмещать багофиксы с фичами, но так получилось)
Добавляет спиннер
Небольшой рефактор кода в части разделения функций модалки и рендеринга с фетчем
> Add spinner and some fixes

- src/js/pagination.js
- src/js/render-card-movie.js
1.Удалила лишнюю переменную const pagesTotal. Она ничего не делала.
2. Поправила function createCardMarkup в render-card-movie c комментарием
3 Прописала комментарии к функциям пагинации
> Bag fix/render card muvie and pagination

- src/js/fetch-my-library.js
- src/sass/modules/_header.scss
изменен bgr, изменен фон после выбора инпута ранее введенного слова, увеличена задержка, плавность смены bgr
> mini-bagfix-header

- src/js/pagination.js
- src/js/render-on-click-movie.js
1. Поправила спиннер при клике на постер.
2. Заменила стрелочки в пагинации
> bag fix spinner & arrow

- src/js/class-api-service.js
- src/js/get-refs.js
- src/js/render-on-click-movie.js
- src/js/render-on-click-video.js
- src/sass/modules/_pagination.scss
- src/templates/movie-modal-card.hbs
- src/templates/movie-video-card.hbs
1. Добавляет фетч для видео
2. Получает id фильма для дальнейшего рендаринга видео по id
3.добавляет шаблон hbs для разметки видео
4. почистила лишние стили
> add fetch for video

- src/index.js
- src/js/class-api-service.js
- src/js/fetch-my-library.js
- src/js/render-movies-grid.js
- src/js/return-home-logo.js
- src/js/toogle-popular-movies.js
- src/partials/gallery.html
- src/partials/header.html
- src/sass/main.scss
- src/sass/modules/_gallery.scss
- src/sass/modules/_header.scss
- src/sass/modules/_render-popular-to-week.scss
Добавлена кнопочка рендера страницы популярных за 1 неделю или 1 день
> toggle-popular-movies

- src/images/svg/icon-close.svg
- src/index.html
- src/js/pagination.js
- src/js/render-on-click-video.js
- src/partials/modal-video.html
- src/sass/main.scss
- src/sass/modules/_modal-video.scss
- src/templates/movie-modal-card.hbs
- src/templates/movie-video-card.hbs
1. добавила модалку для видео.
2. прописала функции открытия, закрытия.
3. добавила кнопку для открытия модалки
> add modal window for video

- src/js/render-on-click-video.js
1. Поправила рендер видео, сделала сброс шаблона, при закрытии модалки.
> bag-fix render video for close modal

- src/js/render-on-click-video.js
Поправляет отображение кнопки на количество тизеров в массиве
> add bag-fix for btn Teaser

- src/js/get-refs.js
- src/js/render-movies-grid.js
- src/js/return-home-logo.js
- src/js/toogle-popular-movies.js
- src/sass/modules/_render-popular-to-week.scss
Исправлены некоторые мелкие баги ширины чекбокса, при нажатии на поиск по запросу скрывается чекбокс выбора популярных
> bag-fix-chek-popular

- src/js/pagination.js
- src/js/return-home-logo.js
Поправила логику отображения дефолтной страницы при возврате из Библиотеки
> Fix Home return logic

- src/images/svg/icon-close-black.svg
- src/partials/modal.html
- src/sass/modules/_modal.scss
Поправила стили кнопки закрытия модалки, ибо именно клик на нее вызывал ошибку в консоли
> Fix styles of modal close btn

- src/js/fetch-my-library.js
- src/js/pagination.js
- src/js/return-home-logo.js
- src/sass/modules/_header.scss
1.закоментила файл retyrn-home logo
2.закоментила файл fetch my library
3. всё добавила в пагинацию и, перешерстила, можно переименовать файл в навигацию, наверное будет логичнее теперь.
4. sass файл header не трогала, только посмотрела, а он взял и отпритирился.
> bag-fix/fix-navigation

- src/js/pagination.js
- src/partials/header.html
- src/sass/modules/_header.scss
Поправила хедер, чтобы кнопок было по одной
> Fix header markup

- src/index.js
- src/sass/modules/_modal-video.scss
Чуть поправила z-индексы модалки видео
> Little fix of video modal visibility

- src/js/modal-open.js
- src/js/render-on-click-video.js
Поправила, чтобы при закрытии на Esc модалки видео модалка самого фильма не закрывалась сразу, а независимо при нажатии на Esc еще раз
> Add fix for ESC close modals logic

- src/js/get-refs.js
- src/js/navigation.js
- src/js/toogle-popular-movies.js
- src/partials/gallery.html
- src/partials/header.html
Исправлено положение маркера чекбокса при переходе на хом или лого
> bag-fix-toggl

- src/js/ls-add-to-queue.js
- src/js/ls-add-to-watched.js
- src/js/render-library.js
Перерисовка страницы после удаления последнего элемента в сетке библиотеки во вкладках watched и queue
> рендерн удаления последнего элемента сетки

- src/js/class-api-service.js
- src/js/render-on-click-movie.js
- src/templates/movie-modal-card.hbs
Поправила отрисовку кнопки видео в зависимости от его наличия
> Add fix for teaser button render

- src/js/navigation.js
- src/js/render-library.js
- src/js/render-on-click-video.js
Продолжение правок рендера кнопки видео
> Continue to fix teaser button logic

- package.json
- src/js/render-library.js
- src/partials/gallery.html
Пофиксила ошибку при переходе в пустую библиотеку
> Fix empty library error

- src/js/ls-add-to-watched.js
- src/js/pagination.js
- src/js/render-library.js
Просто закоментила onClickWatched
> Trying to fix Library

- src/js/ls-add-to-queue.js
- src/js/ls-add-to-watched.js
- src/js/render-library.js
> Trying to fix library render logic

- package-lock.json
- src/js/ls-add-to-queue.js
- src/js/ls-add-to-watched.js
Убирает ошибку из консоли и фиксит перерендер последненго элнмента на последней странице при удалении, обратную операцию не делала, закомментила инкременты
> Fix library render better

- src/js/pagination.js
- src/partials/header.html
- src/sass/modules/_modal.scss
Небольшие правки мобильной пагинации
> Fix pagination

- src/js/render-movies-grid.js
- src/sass/modules/_modal-open.scss
- src/sass/modules/_modal-video.scss
- src/sass/utils/_footer-backdrop.scss
- src/sass/utils/_swipe-up.scss
Немного почистила коменты и упорядочила z индексы
> Clean some comments
